-- begin ERP_SUBUNIT
alter table ERP_SUBUNIT add constraint FK_ERP_SUBUNIT_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references ERP_DEPARTMENT(ID)^
create index IDX_ERP_SUBUNIT_ON_DEPARTMENT on ERP_SUBUNIT (DEPARTMENT_ID)^
-- end ERP_SUBUNIT
-- begin ERP_WORK_EXPERIENCE
alter table ERP_WORK_EXPERIENCE add constraint FK_ERP_WORK_EXPERIENCE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID)^
create index IDX_ERP_WORK_EXPERIENCE_ON_EMPLOYEE on ERP_WORK_EXPERIENCE (EMPLOYEE_ID)^
-- end ERP_WORK_EXPERIENCE
-- begin ERP_EMPLOYEE_LANGUAGE
alter table ERP_EMPLOYEE_LANGUAGE add constraint FK_ERP_EMPLOYEE_LANGUAGE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID)^
alter table ERP_EMPLOYEE_LANGUAGE add constraint FK_ERP_EMPLOYEE_LANGUAGE_ON_LANGUAGE foreign key (LANGUAGE_ID) references ERP_LANGUAGE(ID)^
create unique index IDX_ERP_EMPLOYEE_LANGUAGE_UNIQ_LANGUAGE_ID on ERP_EMPLOYEE_LANGUAGE (LANGUAGE_ID) ^
create index IDX_ERP_EMPLOYEE_LANGUAGE_ON_EMPLOYEE on ERP_EMPLOYEE_LANGUAGE (EMPLOYEE_ID)^
create index IDX_ERP_EMPLOYEE_LANGUAGE_ON_LANGUAGE on ERP_EMPLOYEE_LANGUAGE (LANGUAGE_ID)^
-- end ERP_EMPLOYEE_LANGUAGE
-- begin ERP_EMPLOYEE_EDUCATION
alter table ERP_EMPLOYEE_EDUCATION add constraint FK_ERP_EMPLOYEE_EDUCATION_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID)^
alter table ERP_EMPLOYEE_EDUCATION add constraint FK_ERP_EMPLOYEE_EDUCATION_ON_EDUCATION foreign key (EDUCATION_ID) references ERP_EDUCATION(ID)^
create unique index IDX_ERP_EMPLOYEE_EDUCATION_UNIQ_EDUCATION_ID on ERP_EMPLOYEE_EDUCATION (EDUCATION_ID) ^
create index IDX_ERP_EMPLOYEE_EDUCATION_ON_EMPLOYEE on ERP_EMPLOYEE_EDUCATION (EMPLOYEE_ID)^
create index IDX_ERP_EMPLOYEE_EDUCATION_ON_EDUCATION on ERP_EMPLOYEE_EDUCATION (EDUCATION_ID)^
-- end ERP_EMPLOYEE_EDUCATION
-- begin ERP_EMPLOYEE_SKILL
alter table ERP_EMPLOYEE_SKILL add constraint FK_ERP_EMPLOYEE_SKILL_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID)^
alter table ERP_EMPLOYEE_SKILL add constraint FK_ERP_EMPLOYEE_SKILL_ON_SKILL foreign key (SKILL_ID) references ERP_SKILL(ID)^
create index IDX_ERP_EMPLOYEE_SKILL_ON_EMPLOYEE on ERP_EMPLOYEE_SKILL (EMPLOYEE_ID)^
create index IDX_ERP_EMPLOYEE_SKILL_ON_SKILL on ERP_EMPLOYEE_SKILL (SKILL_ID)^
-- end ERP_EMPLOYEE_SKILL
-- begin ERP_DEPARTMENT
create unique index IDX_ERP_DEPARTMENT_UNIQ_DEPARTMENT on ERP_DEPARTMENT (DEPARTMENT) ^
-- end ERP_DEPARTMENT
-- begin ERP_LANGUAGE
create unique index IDX_ERP_LANGUAGE_UNIQ_NAME on ERP_LANGUAGE (NAME) ^
-- end ERP_LANGUAGE
-- begin ERP_EDUCATION
create unique index IDX_ERP_EDUCATION_UNIQ_NAME on ERP_EDUCATION (NAME) ^
-- end ERP_EDUCATION
-- begin ERP_SKILL
create unique index IDX_ERP_SKILL_UNIQ_NAME on ERP_SKILL (NAME) ^
-- end ERP_SKILL
-- begin ERP_EMPLOYEE
alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references ERP_DEPARTMENT(ID)^
alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_ON_SUBUNIT foreign key (SUBUNIT_ID) references ERP_SUBUNIT(ID)^
create unique index IDX_ERP_EMPLOYEE_UNIQ_NIC on ERP_EMPLOYEE (NIC) ^
create unique index IDX_ERP_EMPLOYEE_UNIQ_EMP_ID on ERP_EMPLOYEE (EMP_ID) ^
create unique index IDX_ERP_EMPLOYEE_UNIQ_MOBILE_PHONE on ERP_EMPLOYEE (MOBILE_PHONE) ^
create unique index IDX_ERP_EMPLOYEE_UNIQ_EMAIL on ERP_EMPLOYEE (EMAIL) ^
create index IDX_ERP_EMPLOYEE_ON_DEPARTMENT on ERP_EMPLOYEE (DEPARTMENT_ID)^
create index IDX_ERP_EMPLOYEE_ON_SUBUNIT on ERP_EMPLOYEE (SUBUNIT_ID)^
-- end ERP_EMPLOYEE
