alter table ERP_CATALOG_PRODUCT add constraint FK_ERP_CATALOG_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references ERP_PRODUCT(ID);
create index IDX_ERP_CATALOG_PRODUCT_ON_PRODUCT on ERP_CATALOG_PRODUCT (PRODUCT_ID);
