alter table ERP_CATALOG_PRODUCT add constraint FK_ERP_CATALOG_PRODUCT_ON_CATEGORY foreign key (CATEGORY_ID) references ERP_PRODUCT_CATEGORY(ID);
create index IDX_ERP_CATALOG_PRODUCT_ON_CATEGORY on ERP_CATALOG_PRODUCT (CATEGORY_ID);
