alter table ERP_SUBUNIT add constraint FK_ERP_SUBUNIT_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references ERP_DEPARTMENT(ID);
alter table ERP_SUBUNIT add constraint FK_ERP_SUBUNIT_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID);
create index IDX_ERP_SUBUNIT_ON_DEPARTMENT on ERP_SUBUNIT (DEPARTMENT_ID);
create index IDX_ERP_SUBUNIT_ON_EMPLOYEE on ERP_SUBUNIT (EMPLOYEE_ID);
