alter table ERP_EMPLOYEE_SKILL add constraint FK_ERP_EMPLOYEE_SKILL_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID);
alter table ERP_EMPLOYEE_SKILL add constraint FK_ERP_EMPLOYEE_SKILL_ON_SKILL foreign key (SKILL_ID) references ERP_SKILL(ID);
create index IDX_ERP_EMPLOYEE_SKILL_ON_EMPLOYEE on ERP_EMPLOYEE_SKILL (EMPLOYEE_ID);
create index IDX_ERP_EMPLOYEE_SKILL_ON_SKILL on ERP_EMPLOYEE_SKILL (SKILL_ID);
