alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_ON_NATIONALITY foreign key (NATIONALITY_ID) references ERP_COUNTRY(ID);
create index IDX_ERP_EMPLOYEE_ON_NATIONALITY on ERP_EMPLOYEE (NATIONALITY_ID);
