alter table ERP_EMPLOYEE_LICENSE add constraint FK_ERP_EMPLOYEE_LICENSE_ON_LICENSE foreign key (LICENSE_ID) references ERP_LICENSE(ID);
alter table ERP_EMPLOYEE_LICENSE add constraint FK_ERP_EMPLOYEE_LICENSE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID);
create unique index IDX_ERP_EMPLOYEE_LICENSE_UNIQ_LICENSE_NUMBER on ERP_EMPLOYEE_LICENSE (LICENSE_NUMBER) ;
create index IDX_ERP_EMPLOYEE_LICENSE_ON_LICENSE on ERP_EMPLOYEE_LICENSE (LICENSE_ID);
create index IDX_ERP_EMPLOYEE_LICENSE_ON_EMPLOYEE on ERP_EMPLOYEE_LICENSE (EMPLOYEE_ID);
