alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references ERP_DEPARTMENT(ID);
alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_ON_SUBUNIT foreign key (SUBUNIT_ID) references ERP_SUBUNIT(ID);
create unique index IDX_ERP_EMPLOYEE_UNIQ_NIC on ERP_EMPLOYEE (NIC) ;
create unique index IDX_ERP_EMPLOYEE_UNIQ_EMP_ID on ERP_EMPLOYEE (EMP_ID) ;
create unique index IDX_ERP_EMPLOYEE_UNIQ_MOBILE_PHONE on ERP_EMPLOYEE (MOBILE_PHONE) ;
create unique index IDX_ERP_EMPLOYEE_UNIQ_EMAIL on ERP_EMPLOYEE (EMAIL) ;
create index IDX_ERP_EMPLOYEE_ON_DEPARTMENT on ERP_EMPLOYEE (DEPARTMENT_ID);
create index IDX_ERP_EMPLOYEE_ON_SUBUNIT on ERP_EMPLOYEE (SUBUNIT_ID);
