-- begin ERP_DEPARTMENT
create unique index IDX_ERP_DEPARTMENT_UK_DEPARTMENT on ERP_DEPARTMENT (DEPARTMENT) where DELETE_TS is null ^
-- end ERP_DEPARTMENT
-- begin ERP_EMPLOYEE
alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references ERP_DEPARTMENT(ID)^
alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_ON_SUBUNIT foreign key (SUBUNIT_ID) references ERP_SUBUNIT(ID)^
create unique index IDX_ERP_EMPLOYEE_UK_MOBILE_PHONE on ERP_EMPLOYEE (MOBILE_PHONE) where DELETE_TS is null ^
create unique index IDX_ERP_EMPLOYEE_UK_EMP_ID on ERP_EMPLOYEE (EMP_ID) where DELETE_TS is null ^
create unique index IDX_ERP_EMPLOYEE_UK_NIC on ERP_EMPLOYEE (NIC) where DELETE_TS is null ^
create unique index IDX_ERP_EMPLOYEE_UK_EMAIL on ERP_EMPLOYEE (EMAIL) where DELETE_TS is null ^
create index IDX_ERP_EMPLOYEE_ON_DEPARTMENT on ERP_EMPLOYEE (DEPARTMENT_ID)^
create index IDX_ERP_EMPLOYEE_ON_SUBUNIT on ERP_EMPLOYEE (SUBUNIT_ID)^
-- end ERP_EMPLOYEE
-- begin ERP_SUBUNIT
alter table ERP_SUBUNIT add constraint FK_ERP_SUBUNIT_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references ERP_DEPARTMENT(ID)^
create index IDX_ERP_SUBUNIT_ON_DEPARTMENT on ERP_SUBUNIT (DEPARTMENT_ID)^
-- end ERP_SUBUNIT
